spring:
    application:
        name: FilesService
    datasource:
        url: jdbc:postgresql://files-postgres:5432/files_db
        username: files
        password: files
        driver-class-name: org.postgresql.Driver
    jpa:
        how-sql: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
    liquibase:
        enabled: false

grpc:
    server:
        address: 0.0.0.0
        port: 9090
        negotiationType: PLAINTEXT

logging:
    level:
        root: DEBUG
